### ISSUE TITLE
Explain Caching and Cache Strategy in the install Docs

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#1]
First: great work on this library - I'm throwing out our app's version of this solution because it isn't as feature complete and because we don't open source things yet.

Thus, I'm being asked about things like cache time to live for responses and cache clearing. 

There doesn't seem to be any cache related actions available - do you not run into staleness problems on reads?

**Comment by ryanashcraft** [comment]
Thanks for the suggestion. There's a lot more we should explain in documentation, but it's hard to figure out what areas to focus on. So it's good to hear what people think is lacking.

Admittedly, redux-query's caching story is pretty basic. For stale reads, most of of the time we simply set `force: true` in the request query config whenever we want something to always re-query when a component remounts or updates. Note this doesn't prevent you from reading from `entities` when a query is made, so the existing data can continue to be rendered (or not – you could hide the data and show a loading indicator instead).

One mechanism for clearing data from `entities` is the [`remoteEntity` action](https://github.com/amplitude/redux-query/blob/master/src/actions/index.js#L128).

Currently, there are not any mechanisms for getting expiration times or LRU-like behavior out-of-the-box. We have some workarounds for this in Amplitude, but it'd be great to find a generalizable solution.

**Comment by ryanashcraft** [comment]
@MrNice When creating the query config you can use `lastUpdated` from the queries reducer/selector to conditionally set `force: true`. I feel like that should handle the staleness issue you're concerned about.

**Comment by erickreutz** [comment]
@ryanashcraft I see that `removeEntities` has been replaced with `updateEntities`. My problem is even if I remove the entities when the component is re-mounted the entities are not re-fetched because the original query state is still there. How do we suggest we get around that?

**Comment by MrNice** [comment]
You can either choose to call props.forceRequest in a component lifecycle
method or you can delete the query metadata in the queries reducer when the
component unmounts.

**Comment by rplotkin** [comment]
I've added an "expires: {time in ms}" property to my pull request's second commit. It's a very simple addition to requestAsync that could certainly be made fancier with the implementation of something like moment, and the naming might be better as ttl (to line up with Ladda). Still, this seems better than a lot of querying by selectors for what seems to be an important caching task (cache expiration). An alternative would be implementing something like redux-persist's method for clearing out expired requests, but I think that's overkill here.
