### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#114]
Does redux-query have typescript support already?

Thanks!

**Comment by ryanashcraft** [comment]
@samuelcastro redux-query doesn't currently have a typescript interface. See #89 where someone else made an attempt. You may be able to use some of their types. As a side note, it would be awesome if someone contributed a redux-query typescript interface to the DefinitelyTyped repo!

**Comment by karevn** [comment]
I have it in my TODO, but no promises on the timeline for now.

**Comment by karevn** [comment]
https://github.com/amplitude/redux-query/pull/131

**Comment by rctbusk** [comment]
@karevn addressed this issue and redux-query 3.1.1 should now support typescript typings

**Comment by samuelcastro** [comment]
That's great, good job guys!
