### ISSUE TITLE
Request Retry

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#119]
How to define a max request retry when some failure occurs?

**Comment by ryanashcraft** [comment]
@samuelcastro You can override the retry behavior via the config param for the middleware. See https://github.com/amplitude/redux-query/blob/e9e6eaea56564189d370b4573015b57b1f1f9c69/src/middleware/query-advanced.js#L24-L28

Side note: we should document this in the README.

**Comment by samuelcastro** [comment]
Thanks @ryanashcraft that's what I need.
