### ISSUE TITLE
Example with redux-saga

### ISSUE THREAD

**Issue by mike623** [amplitude/redux-query#12]
That is what I want!  Gd job bro!  I also want to know that do any case you experienced to integrate saga with redux-query?

**Comment by vomchik** [comment]
@mike623 What exactly you will want to know?)

**Comment by ryanashcraft** [comment]
@mike623 @vomchik check out https://amplitude.github.io/redux-query/#/redux-saga and let me know if you have any feedback!

**Comment by vomchik** [comment]
@ryanashcraft Do you know how get request instance in saga worker?
Now, i do it like this: 
`const { request } = yield take(actionTypes.MUTATE_START); `

**Comment by ryanashcraft** [comment]
@vomchik That should work. I'm curious why you need the request (aka network adapter) instance in a saga though.

**Comment by vomchik** [comment]
@ryanashcraft I need the instance for getting progress when i upload the file.

**Comment by ryanashcraft** [comment]
@vomchik Ok cool. Just heads up, going to be making some backwards incompatible changes with getting the request instance from actions with 2.0: https://github.com/amplitude/redux-query/issues/70
