### ISSUE TITLE
Request middleware 

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#120]
How to build up a redux middleware that would intercept the request headers before it goes out, for example, to automatically include an authentication JWT in the http header.

I know that there is discussion about it here https://github.com/amplitude/redux-query/issues/3 and here https://github.com/amplitude/redux-query/issues/31, but honestly it's not clear how this could be implemented with redux-query.

Thanks.

**Comment by ManThursday** [comment]
Hi @samuelcastro,

If you wanted to add a header like `Authorization: Bearer abc123` to a single request you can do so by adding it to the `options` in the query config e.g.

```javascript
const jwtToken = 'abc123';
const queryConfig = {
  url: '/some-jwt-secured-endpoint',
  options: {
    headers: {
      authorization: `Bearer ${jwtToken}`,
    },
  },
};
dispatch(requestAsync(queryConfig));
```

In order to do this for _every_ request you can apply a [middleware](https://redux.js.org/advanced/middleware) to redux.  It could look something like this:

```javascript
import { actionTypes } from 'redux-query';

const { MUTATE_ASYNC, REQUEST_ASYNC } = actionTypes;
const jwtToken = 'abc123';

const jwtMiddleware = store => next => action => {
  if (action && (action.type === MUTATE_ASYNC || action.type === REQUEST_ASYNC)) {
    // This is a redux-query action so add the JWT header
    const options = action.options || {};
    const headers = options.headers || {};
    const updatedAction = {
      ...action,
      options: {
        ...options,
        headers: {
          ...headers,
          authorization: `Bearer ${jwtToken}`,
      },
    };
    
    // Let the action continue, but now with the JWT header.
    next(updatedAction);
  } else {
    // This isn't a redux-query action so just let it pass through
    next(action);
  }
};
```

**Comment by samuelcastro** [comment]
@ManThursday Thanks, that's exactly what I need!

**Comment by MikeMaven** [comment]
Can we get a Typescript friendly version of this?
