### ISSUE TITLE
Superagent tries to mutate frozen store on timeout

### ISSUE THREAD

**Issue by dizzyone** [amplitude/redux-query#121]
As the title says, we have our store object frozen on develop which was causing errors in Superagent (trying to set length of an array by hand). Unfreezing the store solves this, which is not ideal.

**Comment by ManThursday** [comment]
Hey @dizzyone could you post a stack trace?

**Comment by ryanashcraft** [comment]
@dizzyone 3.0, which was just published, should resolve this issue. The superagent instance is no longer stored in the Redux state. Please see https://amplitude.github.io/redux-query/docs/upgrade-guides/v2-to-v3 for a guide on how to upgrade from v2 to 3.0.
