### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#122]
Hi, I've set `credentials: "include"` in my request options however CORS is still blocking me:

```
Access to XMLHttpRequest at 'https://xxx' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

Related: https://github.com/amplitude/redux-query/issues/28

Any thoughts?

**Comment by samuelcastro** [comment]
I've enabled it on the server-side but still getting this:
```
Access to XMLHttpRequest at 'https://xxx' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by ManThursday** [comment]
Have you been able to confirm that the response includes the expected header with the correct origin in the developer tools?  You may need to use something like Postman to intercept the response, I'm not sure if the browser will show the full details of a rejected response.

Given that the browser is saying that the header isn't there that seems like the area to focus on.  You should be able to reproduce the issue with a raw `XMLHTTPRequest`.  This shouldn't have anything to do with redux-query or superagent.

**Comment by samuelcastro** [comment]
Yeah make sense, I'm closing this issue and keeping debugging, thanks @ManThursday

**Comment by ManThursday** [comment]
Hmm. Is the `Access-Control-Allow-Origin` header present and correct on the `POST` response as well as the `OPTIONS` response?

Sorry I couldn't be more helpful.
