### ISSUE TITLE
Body is not being stringified and appended to the URL as query params.

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#126]
So the documentation says that `body` is stringified and appended to the URL as query params, but for some reason this is not working as far as I could see. 

I can assure that the body is being sent and the method is `GET` however there is not query params being generated and appended.

**Comment by ryanashcraft** [comment]
@samuelcastro The `body` param should be stringified as query params if you're using the default queryMiddleware which uses the superagent network interface. Are you using a custom network interface?

**Comment by samuelcastro** [comment]
@ryanashcraft Yes I am, maybe might be good to describe this in the documentation (if it is already, sorry about that )

**Comment by ryanashcraft** [comment]
@samuelcastro 👍 Added a note in the README.

**Comment by samuelcastro** [comment]
Great, thanks!
