### ISSUE TITLE
Feature Request - Return data on repeated requests.

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#127]
Following up the question I commented here: https://github.com/amplitude/redux-query/issues/77

Is there a way to synchronously return the data rather than undefined on repeated requests?

Thanks.

**Comment by ryanashcraft** [comment]
@samuelcastro I assume you mean that instead it returns the cached result instead? The problem is that we don't store the raw response or a snapshot of the transformed & entities results for every query. It would consume too much memory.

**Comment by samuelcastro** [comment]
@ryanashcraft Isn't doable we store it in the redux store? And enable/disable by configuration.

**Comment by ryanashcraft** [comment]
@samuelcastro I worry that would result in excessive memory usage and wouldn't be an option we'd ever want to recommend.
