### ISSUE TITLE
Testing `connectRequest`ed components

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#13]
How do you test components wrapped in redux-query to ensure your data fetching logic is correct?

Even if my react components are pure, I still test the interactions between state, mapstate, and the pure component's rendering in my tests. When I added connectRequest, I found that jest would throw an error saying "TypeError: requestPromise.then is not a function".

My workaround solution (for Jest testing specifically) is:
```js
connectRequest((props) => {
  const {loading} = props // from mapState
  if (!loading || !!global.jasmine) {
    return undefined
  }

  return {...config}
})
```
Where I'm checking for the global jasmine to tell if we're in tests.

Ideally, I'd like a to have jest mock that lets me ensure that the request was attempted (or not), and can be mocked similarly to this superagent mock: https://github.com/facebook/jest/issues/223#issuecomment-278017346

**Comment by ryanashcraft** [comment]
I don't have a good answer for you right now but open to ideas on how to document or improve testing `connectRequest`ed containers.
