### ISSUE TITLE
More robust and better-documented example

### ISSUE THREAD

**Issue by ryanashcraft** [amplitude/redux-query#15]
The async example is good because it lets you easily compare to the original version from [redux](https://github.com/reactjs/redux/tree/master/examples/async). But it'd be great to build a more complicated example that took advantage of more of redux-query's features:

- mutations
- optimistic updates
- multiple requests in `connectRequest`
- request cancelation
- usage with redux-saga and redux-thunk

**Comment by MrNice** [comment]
@ryanashcraft Willing to work in tandem on docs - if you write the code and explain it in comments I can try to write the docs using your glossary.

**Comment by bstro** [comment]
Need some guidance on how to take advantage of `multiple requests in connectRequest`. Is there a chance this could be lightly documented somewhere (even here) just to get me started?

**Comment by ryanashcraft** [comment]
I've written new examples with some documentation for the site: https://amplitude.github.io/redux-query/#/
