### ISSUE TITLE
useRequest and useMutation not working property with custom middlewares

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#152]
I'm facing a weird issue with `useRequest` and `useMutation` when using a simple custom middleware to change the request `url`. For some reason, with the custom middleware on any new request `queryStatus` is not being returned accordingly.

I've created a codesandbox that reproduces the issue here: https://codesandbox.io/embed/compassionate-platform-04i28

Notice that `queryStatus` will be available just in the first request, any subsequent requests after it  the `useRequest` hook will not re-render providing a new `queryStatus` value. 

Versions:
```
"redux-query": "^3.2.0",
"redux-query-interface-superagent": "^3.2.0",
"redux-query-react": "^3.2.0",
"react": "^16.9.0",
"react-dom": "^16.9.0",
```

Thanks!

**Comment by rctbusk** [comment]
Hey Samuel!

So when running a functional component, the component is run once. The useRequest function, refresh, is the only part of the Component that will be rerun on the button click. 

The only time the alert will be run is on mount of the component. It won't run on every middleware call. Does that make sense?

Ryan

**Comment by samuelcastro** [comment]
@rctbusk It doesn't make sense, this is a hooks right, take out the custom middleware I created you'll see that the alert rerun each new request, that's the correct behaviour.

Thanks.

**Comment by samuelcastro** [comment]
Interesting fact is that if I add a `queryKey` it will work as expected. 🤔

**Comment by rctbusk** [comment]
Sorry for the late response. Redux query relies on being able to look up the query key, by default, the query key includes the URL. So when you change the URL, redux query will not be able to look up the query key. 

There are a couple of ways to fix this, pass in a query key, as you said above, or have your custom middleware map the query key to the original URL passed in.

**Comment by samuelcastro** [comment]
Ohh, that answers it then, do we have this documented somewhere? It'd be great, if it's already there, my apologies. 

Thanks anyway @rctbusk

**Comment by samuelcastro** [comment]
Another question, wouldn't it be better to rely in the queryKey which is constructed from the url rather than look for the url itself?

**Comment by rctbusk** [comment]
I can definitely add some documentation around this. Thanks for pointing it out!
