### ISSUE TITLE
Feature Request - Add useRequests hooks

### ISSUE THREAD

**Issue by mili-confluent** [amplitude/redux-query#158]
`redux-query-react` has the hook: `useRequest` but it did not support requests for multiple requests, so I am planning to create a hook `useRequests` which can send a lot of requests at the same time.

**Comment by rctbusk** [comment]
Hey @mili-confluent, this is actually the next step on the roadmap for redux-query-react. Hopefully will have a PR open in the next week or so along with an alpha release. Would love to get your feedback when I open the PR.

**Comment by mili-confluent** [comment]
Thank you @rctbusk

**Comment by kamranayub** [comment]
@rctbusk Saw this was in the docs and available, I think, but TS is not finding the exported function (wondering if somehow types are out-of-date?)

![image](https://user-images.githubusercontent.com/563819/71921112-cd032680-314d-11ea-9467-5892c33c79e9.png)

**Comment by mili-confluent** [comment]
I find there is a lot of cancel query warning when I use conncetRequest. It seems we did not return the function correctly so that the finished callback did not really delete the pending key. https://github.com/amplitude/redux-query/blob/27828737fb61d5d89e179d53cdd01b1367a84d2f/packages/redux-query-react/src/components/connect-request.js#L91-L95

**Comment by rctbusk** [comment]
These PRs are included in the newest version release. 3.3.1. Let me know if this issues are fixed. Closing this issue unless hearing otherwise.
