### ISSUE TITLE
Allow request throttling for redux-query

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#17]
It might be nice to allow a maximum of 4 pending requests so that the other two requests could be made by other components.
This throttling could be controlled at either the request wrapper level upon initialization, or in the connectRequests.

**Comment by ryanashcraft** [comment]
@MrNice Haven't thought about this much, but I'd imagine it'd be possible to implement some sort of throttling with regular redux middleware that goes before the queryMiddleware.

**Comment by ryanashcraft** [comment]
Closing this issue. If anyone is interested in exploring this – let me know!
