### ISSUE TITLE
Problem with useRequest

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#175]
Hi, I don't know whether this is a bug or a problem with my setup but I can't get `useRequest` work properly, the request is actually being made, however the `update` function is not receiving the entity to update the store like:

```
const [, refresh] = useRequest({
    url: `https://httpbin.org/get`,
    update: {
      users: (old, newValue) => {
        // newValue is always undefined
        debugger;
        return newValue;
      }
    }
  });
```

This is a codesandbox illustrating the problem: https://codesandbox.io/s/zealous-bash-t5m3o

Thanks!

**Comment by Myztiq** [comment]
The data that is being returned does not have a users key in the object. In this case you'd want to use a transform like this: 

https://codesandbox.io/s/wild-river-29bsc

**Comment by samuelcastro** [comment]
Yeah, that make sense, thanks!
