### ISSUE TITLE
Mutations only support HTTP post

### ISSUE THREAD

**Issue by adamsanderson** [amplitude/redux-query#18]
The README states that you can change a mutation's HTTP method via the `options` argument.  It doesn't look like that's actually connected.  In #10 the options hash is now used in mutations to set the headers.

I can extract the logic from the query action and apply it to the mutation logic as well if you'd like.

**Comment by ryanashcraft** [comment]
Good catch. Feel free to make a simple patch if you'd like. 😊

**Comment by ryanashcraft** [comment]
Resolved by #20 and available with `redux-query@next`
