### ISSUE TITLE
Feature request - Debounce

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#181]
It'd be super helpful to have a debounce prop that allows us debounce several requests being made by a period of type, util in an input search for instance.

**Comment by mili-confluent** [comment]
Could you debounce the input onChange event?

**Comment by karevn** [comment]
It looks like @mili-confluent 's idea is great, and debouncing is out-of-scope for this library.

**Comment by samuelcastro** [comment]
Sure, there are several ways to debounce it, and we might not call queries/mutations from onChange events, I just think that this would be super helpful if implemented directly in the library.
