### ISSUE TITLE
Can't use useRequest with Typescript

### ISSUE THREAD

**Issue by sidneytang-elation** [amplitude/redux-query#187]
I have a Typescript project and I can't use useRequest because Typescript is telling me there is no `useRequest` export in `redux-query-react`. I looked through a few other issues and found that this apparently used to be exported, but was removed in this commit? https://github.com/amplitude/redux-query/commit/bab3d7da9b4ef4fdfc8d9bd77a3565d6d95c71ab#diff-6560448a080ef5c9bbbe2bfcd44c739d

Was this intentional? Can useRequest be added back so Typescript users can use the hooks?

**Comment by davishooly** [comment]
🤒   I just realized that my codebase has been heavily affected by the changes merged above. 

@siegcollado  Is there a way that we can access `useRequest`, `useRequests`  and `useMutation` apart from 

 ` import { useMutation } from 'redux-query-react'`?

**Comment by siegcollado** [comment]
im not sure why i added the last commit, but it definitely is not correct. Sorry for not catching this earlier. 

created a pr for this: https://github.com/amplitude/redux-query/pull/188

**Comment by davishooly** [comment]
@siegcollado thanks for the quick reply.

**Comment by rctbusk** [comment]
Hey @davishooly and @siegcollado! This should now be deployed as version 3.4.2. Let me know if this works for you.

**Comment by davishooly** [comment]
@rctbusk version 3.4.2 works well for me thanks.
