### ISSUE TITLE
Universal / Server Side Rendering?

### ISSUE THREAD

**Issue by peterpme** [amplitude/redux-query#19]
Hey,

Great job putting this library together! I see INFO states something about server side mutations. Do you use this for fetching data on the server as well?

Thanks!

**Comment by ryanashcraft** [comment]
@peterpme Server-side rendering hasn't been a focus for redux-query. I'd imagine it's possible to get it working at least to some degree, but I haven't tried.

**Comment by simenbrekken** [comment]
There's a number of different ways this can be implemented. 

The easiest is probably what [Next.js](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle) does with a static `getInitialProps` method on "route" components that returns a promise.

A bit more complicated is how Apollo resolves deeply nested queries using [getDataFromTree](http://dev.apollodata.com/react/server-side-rendering.html#getDataFromTree).

Lastly, I've put together a third alternative that uses a separate "resolver" in which you register promises in `componentWillMount`. I've put up bits of the implementation in [this gist](https://gist.github.com/simenbrekken/ff49428c2ce7676c032318cf16e7a8b4).

**Comment by ryanashcraft** [comment]
Closing this issue. redux-query should work on the server, it just doesn't support automatic requests via `connectRequest`. If someone would like to seriously explore this, let me know!

**Comment by simenbrekken** [comment]
@ryanashcraft I'm deploying an e-commerce site based off the last approach into production next week and I'd be more than happy to share our final implementation.

**Comment by ryanashcraft** [comment]
@simenbrekken Absolutely!

**Comment by simenbrekken** [comment]
@srosset81 The final implementation is pretty much identical to my previous gist but I've updated it include some more bits here: 

https://gist.github.com/simenbrekken/aaa8c978b30f4fc229ab3faec2892f5b

The important part is that `componentWillMount` calls `registerRequestPromises` which on the server gathers a list of promises and resolves them all before rendering. You can also specify a maximum number of rendering iterations you want to perform if you're dealing with nested components (e.g. A fetches some data that it passes to B via props, which in turn fetches some other data based on those). On the client `registerRequestPromises` is essentially a no-op. 

What we like about this approach is how easy you can specify which components to render on the server, which is great for caching. Anything tied to the currently logged-in user isn't server-rendered but fetched after the initial server-side render
