### ISSUE TITLE
Allow control over which redux state slices get updated

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#2]
Almost finished integrating this into the app

This library assumes that all of my entities live together underneath an entities state slice in the redux store.
```js
{
    entities: {
        user: {},
        post: {}
    }
}
```

One thing I want is to be able to use the keys and reducers we've already built out, which are flatter:
```js
{
    user: {},
    post: {},
    ... other stuff ...
    configuration: {},
}
```

The update functionality is really slick and sensible if you're not migrating from a different structure already.

I'll be making a patch for us, which will probably be adding a lookup string. Also, I spent waaaaaay too long reading into the coupling between transform and update, but maybe that's a me problem.

**Comment by MrNice** [comment]
Workaround is simple though: dispatch actions from the update handler

**Comment by ryanashcraft** [comment]
Closing this issue out as it's not something that we're going to support.

In case anyone else comes upon this issue: if you absolutely need to have entities state in some other location, here's a workaround: you can have any reducers make state changes with the REQUEST_SUCCESS, REQUEST_FAILURE, MUTATE_SUCCESS, and MUTATE_FAILURE action types exported from redux-query. Although if you want to do this for all your entities, redux-query is probably not a good fit for you.
