### ISSUE TITLE
Question about where to put side effects

### ISSUE THREAD

**Issue by TheCarlR** [amplitude/redux-query#203]
If there's a need to store a single identifier in for instance localstorage, based on the content of some api call managed by redux-query. Where would you suggest to handle that?
Is there any part in redux query that's suitable? Is redux middleware better/worse?
Handle manually outside useMutation and useSelector?

The identifier in this case would be fetched from part of an api answer the very first time accessing the app, and then stored in localstorage. For all subsequent times it would be fetched from localstorage and be used in the arguments to the api calls.

**Comment by rctbusk** [comment]
Hmmm, question why this storing in localstorage is important? Do you need it to persist across every session?

I ask this because if you are making the call at the start of each session, why not just store this in the redux store for that session.

**Comment by TheCarlR** [comment]
We need it to restore the last session from API. :)

**Comment by rctbusk** [comment]
ahhhh gotcha

If this can happen with any network call coming through redux-query, I would say adding a middleware is probably the easiest.

If it is one specific network call that does this, I would handle outside of useMutation, as to not add unnecessary steps that only one call uses.

**Comment by TheCarlR** [comment]
If I would go with a middleware, is it possible to filter so I only react
on updates on a specific entity?

**Comment by rctbusk** [comment]
Hmmm. Probably not. You could have it check to see if the value stored in redux-query matches the one in localstorage, and if it doesn't match, then update the localstorage value. Sorry it is a bit hacky.
