### ISSUE TITLE
Documentation Sketch

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#24]
Here's how I use redux-query:
![toto_client_overview](https://cloud.githubusercontent.com/assets/2587335/23343735/274d4c4e-fc25-11e6-9fb6-ce3483b7dde9.png)

**Comment by ryanashcraft** [comment]
Thanks for sharing, @MrNice! Awesome diagram. I'm currently doing some thinking and experimentation around documentation and how to explain redux-query to people of different backgrounds and experience levels.

Have you seen similar diagrams for regular redux usage or similar libraries? Curious how others have illustrated similar lifecycles/architectures.

**Comment by MrNice** [comment]
Just remove the yellow and it's react redux. But no, this is our internal
architecture description I had to make for teaching

**Comment by MrNice** [comment]
Senior: "Redux-query: It's a gap layer api that mirrors relay but for RESTful entity graphs instead of GraphQL or Falcor JSON graphs."

**Comment by MrNice** [comment]
Junior: It's a way to tell a react component how to populate an in memory database with server data.
