### ISSUE TITLE
Add HTTP middleware pipeline to handle response

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#31]
Would give us a good foundation to build other tools to solve: #9, #1, #2

Since HTTP is both a protocol and an application data transport system, it has two parts: the metadata and the body.

Middleware systems work by letting the metadata control the response flow.

The current `update: ((old, new) => {})` system could easily be implemented in such a middleware as long as the middleware layer is aware of the redux-store, which is easy enough to provide.

This api would also allow you to mix and match middleware on a per-request config basis, similarly to:

```
const opportunityRenameFields = {
    'opportunity_status': 'status',
}
const opportunityIgnoredFields = [
    'creator_id',
]
export const opportunity = new schema.Entity('opportunity', {}, {
    // vvvvvvvvvvvvvvvvvv
    processStrategy: flow(
        rename(opportunityRenameFields),
        strip(opportunityIgnoredFields),
        camel
    ),
    // ^^^^^^^^^^^^^^^^^^^^
})
```

**Comment by ryanashcraft** [comment]
@MrNice I'm having a tough time understanding your suggestion. Can you please elaborate? Perhaps it'd be useful to come up with an example where this would be useful or demonstrate how this enables things that redux-query can't (at least elegantly) support today?
