### ISSUE TITLE
React Native build faild

### ISSUE THREAD

**Issue by vomchik** [amplitude/redux-query#32]
After installing and configuration I got error

> Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░  47.8% (264/382)...(node:33907) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3676): SyntaxError: TransformError: /Users/vomchik/Projects/node_modules/redux-query/src/index.js: [BABEL] /Users/vomchik/Projects/node_modules/redux-query/src/index.js: Unknown option: /Users/vomchik/Projects/node_modules/react/react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.
 A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
 Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`
For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.Bundling `index.android.js`

Any ideas?

**Comment by vomchik** [comment]
Probably it's problem this old babel version. 
Locally i updated the babel to the last version and it's work.

**Comment by ryanashcraft** [comment]
@vomchik Was the fix to update babel in your project?

**Comment by vomchik** [comment]
Yes, after updating everything works fine.

**Comment by vomchik** [comment]
I clone redux-query repo and update babel to newest version.

**Comment by vomchik** [comment]
Can you update babel-cli ?

**Comment by vomchik** [comment]
And also, why you using very old version of superagent ?

**Comment by vomchik** [comment]
@ryanashcraft The issue can be closed. I installed all required babel-presets to my project and now all works fine.
