### ISSUE TITLE
Redux Query for ImmutableJS

### ISSUE THREAD

**Issue by mmalfertheiner** [amplitude/redux-query#34]
Hi,

I created a fork for this great library, that works with a redux store based on ImmutableJS. If somebody is interested please checkout [redux-query-immutable]( https://github.com/holidu/redux-query-immutable).

**Comment by rogovdm** [comment]
Nice! 

Couple of questions. Why not pull request? What problem did you solve? (I'm using immutable js and redux-query just fine)

**Comment by mmalfertheiner** [comment]
I had to change the core of redux-query as well, in order that I never have to make toJS() on the redux store. I saw your [proposal](https://github.com/amplitude/redux-query/issues/30) as well, but in that case you translate the store to JS each time you pass it to the reducer. This causes new references for every object in the redux-store, which has the effect that you can not make shallow comparisons in the components anymore. Let me try to explain it with an example:

I have the following structure:

`"entities": {
  "users": [
    {
      "id": 1,
      "name": "Bart"
    },
    {
      "id": 2,
      "name": "Lisa"
    },
    {
      "id": 3,
      "name": "Maggie"
    },
  ]
}`

If you would change now only a single user of the list, than you want to have a new reference for entities, users and the user that you changed, but not for the other users.

The changes I made are not compatible with the original library, thats why I made a new package for it. The functionality stays the same and my goal is to merge any changes to redux-query also into the redux-query-immutable project.
