### ISSUE TITLE
Initial reducer state

### ISSUE THREAD

**Issue by superquest** [amplitude/redux-query#43]
Initially, the "entities" reducer state is just an empty object and there doesn't seem to be a way to initialize default state. Consequently my selectors have to check whether `state.entities.someEntity` exists — which is cumbersome and verbose.

How do you deal with this situation? Is there a way to set initial state that I'm just not seeing? If not, do you plan to add it?

Thanks!

**Comment by rogovdm** [comment]
> there doesn't seem to be a way to initialize default state

Huh? Will using default redux API for setting default state helps? `createStore` allows you to pass initial state. pass it something like this:
````javascript
{
  entities: {}
}
````

**Comment by ryanashcraft** [comment]
@rogovdm That's a great suggestion. I wouldn't have thought of that. @superquest does that work for you?

**Comment by superquest** [comment]
Yea that will work. Thanks @rogovdm.
