### ISSUE TITLE
redux-query for ngrx/Angular

### ISSUE THREAD

**Issue by isaacplmann** [amplitude/redux-query#49]
I'm working on a port of this library to use [ngrx](https://github.com/ngrx/store) with [Angular](https://angular.io/).

I had to rewrite the `queryMiddleware` and I obviously can't use the `connectRequest` HOC, but the reducers, actions and selectors are a straight drop in.  However, since you import React at the root level of your distributed package, I can't use your library as a dependency without forcing all my Angular users to also ship React with their apps.  Can you move the React import to the `connectRequest` component itself?

I'd love to be able to easily take advantage of any work you do on reducers, selectors and actions without duplicating effort.

**Comment by ryanashcraft** [comment]
I don't see how we can do this without making a backwards-incompatible API change, so this probably won't happen in the short-term. If we think this is important, we could make it a part of 2.0. We're just getting started planning what 2.0 will look like.

Curious why you can't reuse queryMiddleware as well. Seems you should be able to? That's where a lot of the meat of the library is anyway.

**Comment by isaacplmann** [comment]
Ngrx is a lot like redux, but it doesn't support middleware.  You have to
use their @ngrx/effects library to accomplish the same thing.

**Comment by ryanashcraft** [comment]
Oh I didn't know that. Hmm. Perhaps a proper fork is the best way to go given all of these constraints?

**Comment by isaacplmann** [comment]
So I figured out that if I import directly from the specific file that I need and don't reference the top index.js file, React doesn't get imported.  Thanks for this library - I think it's awesome and I hope the ngrx/Angular community will like it too.

FYI, My port is [ngrx-query](http://github.com/isaacplmann/ngrx-query).

**Comment by ryanashcraft** [comment]
Ok. Sounds good. 👍 I'll check it out!
