### ISSUE TITLE
Superagent is not available to middleware

### ISSUE THREAD

**Issue by victorandree** [amplitude/redux-query#52]
1.3.0 breaks backwards-compatibility because the `request` in e.g. the `REQUEST_START` action is no longer a superagent instance, but just `{ request, abort }` functions. This breaks any middleware that relied on modifying the superagent instance to centralize e.g. authentication or URL prefixing (as we no longer can use `request.use`, for example).

**Comment by ryanashcraft** [comment]
@victorandree Yeah this is my bad. I totally forgot that we include `request` in the actions. I noticed it the other day and was hoping that no one was relying on it (we don't use it at Amplitude). Will push an update soon.

**Comment by ryanashcraft** [comment]
Fixed with 1.4.0.
