### ISSUE TITLE
What is network-adapter? And are there examples somewhere?

### ISSUE THREAD

**Issue by bdougie** [amplitude/redux-query#59]
Can you expound on what a network-adapter, is this just redux middleware to redux thunk and sagas? I am setting this up to test out for a project at work and find the current explanation in the README quite unclear.

Thanks

**Comment by ryanashcraft** [comment]
@bdougie It's an abstract interface for redux-query to send and abort HTTP requests. For users of redux-query, it's only an important concept to know if you're using `redux-query/advanced` and need to want to use a different library than superagent – or some customized instance of superagent. I'd expect and hope a large majority of redux-query users don't need to use `redux-query/advanced` and worry about adapters, but it's available as an option if you do.

See the adapter we have for superagent: https://github.com/amplitude/redux-query/blob/master/src/adapters/superagent.js

**Comment by bdougie** [comment]
Thanks for the explanation this definitely clear things up. I recently added this to a project while on a flight and misread the README a bit. Now that I re-read, I do not require the use of the advanced library. 

I am looking forward to finishing adding this to my React Native project
