### ISSUE TITLE
Allow multiple URLs to provide data for a component

### ISSUE THREAD

**Issue by MrNice** [amplitude/redux-query#6]
Currently, connectRequest can only make a single request per component per mount, which incentivizes a nice pattern of putting the connectRequest binding to the component that the data is most local to. However, sometimes a component relies on data that cannot be fulfilled by a single request, but the requests don't need to be performed serially (I can see how to use connectRequest + mapState to make iterative requests fairly easily though). This currently isn't supported, but I would like it if the API to do so wouldn't be too confusing, so let's discuss.

The component I had built internally took an array of "requisition" objects which described a URL, a cache key for storage, a normalizing transform, and a dispatch function to call after processing. Perhaps I could simply return an array of config objects from my `mapConfigToProps`?

If this is already supported, sorry for not looking at the code this time.

Thanks again for open sourcing this tool and working with me as I integrate it and push against the assumptions it was created with.

**Comment by ryanashcraft** [comment]
@MrNice This isn't something currently supported but it's something we've wanted for a while. The current suggested workaround is to just wrap your component in multiple `connectRequests`, but this is pretty gross and not great for performance reasons.

Would love to see someone make a PR for this. I'd probably get around to it eventually but might not be for a while.

**Comment by MrNice** [comment]
Made a PR that I haven't actually executed, to show strategy. I'll test it either tonight or this weekend, have a harsh deadline to hit. Let me know what you think, and if you have time, please test the change locally.

Essentially, make your `mapConfigToProps` function return an array of config objects, and these changes should unpack those objects into cache keys and cancel what is unnecessary and request anything else.

This pattern, combined with the boolean flag loading from mapState pattern we talked about, should eliminate most duplicate entity edge cases.

**Comment by MrNice** [comment]
Solved by the pull request

**Comment by bstro** [comment]
@MrNice how is this solved? Currently running into the same problem and not sure how to get around it.

**Comment by MrNice** [comment]
Use `version 1.1.*` and have your mapConfigToProps return an array of
configuration objects.

**Comment by bstro** [comment]
Thanks @MrNice !
