### ISSUE TITLE
Specify certain requests for forceRequest

### ISSUE THREAD

**Issue by bstro** [amplitude/redux-query#62]
`connectRequest` passes a `forceRequest` method to the component, but on execution, it appears to request every item originally passed in to the component. In the case that I've passed in an array of query configurations, would it be possible to request data only from certain query configurations? If this behavior is not already supported, I would be interested in opening a PR for this behavior, if you'd be amenable.

**Comment by simenbrekken** [comment]
I had similar requirements as this along with #19 so I've started writing a replacement for `connectRequest` that accepts an object of queries instead of an array. It's part of a bigger project upgrade but I've put bits of the initial implementation [in a gist](https://gist.github.com/simenbrekken/ff49428c2ce7676c032318cf16e7a8b4).

Component usage:

```js
export default withReduxQuery({
  first: {
    url: '/first'
  },
  
  second: {
    url: '/second'
  },

  third: {
    url: '/third'
  }
})

...

refetchFirst() {
  this.props.refetch('first')
}

refetchSecondAndThird() {
  this.props.refetch(['second', 'third'])
}
```

It would be interesting if `connectRequest` would accept a single config object, an array of configs or a map of configs. `forceRequest` could then be modified to work with all three.

**Comment by ryanashcraft** [comment]
@bstro This is indeed something you can't do today. I think best way to do it is similar to what @simenbrekken has – support `mapPropsToConfig` returning an object, and allow optional params to `forceRequest` of the keys that select which configs to re-request.

Feel free to open a PR for this if you'd like!

**Comment by acontreras89** [comment]
You can set the `force` property to `false` in those configs that don't need to be re-evaluated.
Although this is not a solution to your problem, it may be just enough in certain situations (namely, when you can know what configs need to be re-evaluated in your `mapPropsToQuery`.)

Setting the `force` property will override [`connectRequest`'s flag](https://github.com/amplitude/redux-query/blob/master/src/components/connect-request.js#L100-L102), resulting in the config being skipped by [the middleware](https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L94) (as long as it's already been requested.)

**Comment by rogovdm** [comment]
Another way is to create a separate Container component with a single query config. Thus we will have a forceRequest binded just to that request.

**Comment by rogovdm** [comment]
Also, we can try to teach `forceReqeust` to accept a query key to specify a request. That query key can be passed via an object or calculated dynamically via exposed `getQuery` method.

**Comment by ryanashcraft** [comment]
Closing this issue for now. If you need this specific behavior, you can simply dispatch map `requestAsync` and `mutateAsync` actions to props with react-redux's `mapDispatchToProps`.
