### ISSUE TITLE
Support for Deduplicating Requests Containing Multiple IDs

### ISSUE THREAD

**Issue by mutewinter** [amplitude/redux-query#64]
A common use case in an app I'm building is fetching data for a listing view using a bulk ID endpoint, then transitioning to a detail page.

## Listing Page

```
/api/posts?ids=1,2,3
```

## Detail Page

```
/api/posts?ids=1
```

It would be wonderful if redux-query exposed a custom method on the adapter (or anywhere else) to allow me to tell it what is or isn't a duplicate request. Right now, we're suffering a request for multiple IDs and then another for a single ID when the user transitions to the detail page.

P.S. love the library and amazing work.

**Comment by ryanashcraft** [comment]
@mutewinter Have you tried specifying a `queryKey` value? https://github.com/amplitude/redux-query#request-query-config-options

**Comment by mutewinter** [comment]
It doesn't seem possible to generate a queryKey that would match a url with 1 and 2, 1 only, and 2 only. Perhaps if a queryMatcher API were provided?

**Comment by rogovdm** [comment]
@mutewinter 

`connectRequest` has the following signature: `connectRequest(props => arr)`.

In your `DetailPageContainer`you can select post with id `1` and set it to props. (Big chances 
you've already doing this). And what is left is to check in `connectRequest`, whether we've already have data about post with id `1`.

````javascript
  connectRequest(({ id, post }) => !!post ? getQueryConfig(id) : [])
````

Hope this works, cheers.

**Comment by mutewinter** [comment]
> In your DetailPageContaineryou can select post with id 1 and set it to props

Good point. I'm essentially doing this right now, but also still allowing the extra network request to go through. I'll close this since this solution does work. Thanks for the feedback, and again for the library.
