### ISSUE TITLE
Mark requests as obsolete

### ISSUE THREAD

**Issue by acontreras89** [amplitude/redux-query#65]
Say you have a paginated list that uses `connectRequest` to load each page. Something like:

```js
const mapPropsToQuery = (props) => ({
  url: '/api/users',
  body: { page: props.currentPage },
  update: { users: updateUsers }
})

export default connectRequest(mapPropsToQuery)(UsersList)
```

Say `UserList` renders a delete button for each user. Upon deletion of a user, the current page and all subsequent pages will need to be re-evaluated.

Current page can be requested again by using `forceUpdate`. However, there's no simple way to let `redux-query` know that other pages should be fetched again when necessary.

**Comment by rogovdm** [comment]
Why not something like this?

````javascript
const mapPropsToQuery = ({ lastUserDeletedIndex, currentPage }) => ({
  force: shouldForceUpdate(lastUserDeletedIndex)
  url: '/api/users',
  body: { page: currentPage },
  update: { users: updateUsers }
})
````

````shouldForceUpdate```` can be lifted into other place (like `mapStateToProp`) which has access to state.

The idea is to track data about deleted user to calculate `force` based on that value.

**Comment by acontreras89** [comment]
@rogovdm thanks for writing!

I did try something like that. However, I found that setting the `force` flag inside `mapPropsToQuery` does not actually force request re-execution. [Only `queryString` is used](https://github.com/amplitude/redux-query/blob/master/src/components/connect-request.js#L52-L67) to check for new requests.

**Comment by ryanashcraft** [comment]
@acontreras89 `force: true` won't retrigger the request if the query config doesn't change and the component wasn't unmounted/remounted.

Typically the recommended pattern would be that when the user is deleted, it would return down all entities that would possibly be affected. Alternatively, promise-chain on the initial request and manually dispatch requestAsync actions with `force: true` in the `then` callback.

**Comment by acontreras89** [comment]
@ryanashcraft let me explain my scenario a little further:

Deleting an entity does not have any side effects on other entities, but paginated requests will return different results for the page it belonged to and all subsequent pages. 

On deletion, the server responds with `204 (No Content)`.

If deletion is performed from the _list page_ component, calling `forceRequest` will fetch the page again. However, other pages may already have been requested already, and we will need to load again them if (and only if) revisited by the user.

**Comment by acontreras89** [comment]
After playing a bit more, I've been able to implement this by using both `forceRequest` to reload the current page and setting the `force: true` flag when visiting any invalidated page, as @rogovdm suggested.

`force: true` does not work from an already-mounted component (as pointed out by @ryanashcraft), but it will work if the query config changes (e.g. when navigating through pages.)

**Comment by acontreras89** [comment]
It should also be noted that in order for `forceRequest` to work as expected, the `force` flag must only be set to `true` when necessary. It should not be set to `false` in any case, as it will override the value passed by the HOC.
