### ISSUE TITLE
Problem with ShallowCompare in React Native 0.44

### ISSUE THREAD

**Issue by vomchik** [amplitude/redux-query#75]
Now React Native 0.44 use React 16 beta. 
All react add-ons are was removed from the standard package.

So I get an error when building my project.

> error: bundling: UnableToResolveError: Unable to resolve module `react/lib/shallowCompare` from `/Users/vomchik/Projects/LITS/toolook/toolook-app-react-native/node_modules/react-addons-shallow-compare/index.js`: Module does not exist in the module map or in these directories:
  /Users/vomchik/Projects/LITS/toolook/toolook-app-react-native/node_modules/react/lib

**Comment by ryanashcraft** [comment]
@vomchik Going to migrate off of react-addons-shallow-compare in 2.0. Published a new v2.0.0 release candidate with this change: 2.0.0-rc.2

**Comment by vomchik** [comment]
Cool, thanks.
