### ISSUE TITLE
On repeated request, i am received undefined result

### ISSUE THREAD

**Issue by vomchik** [amplitude/redux-query#77]
If we repeat the same request we received an undefined instead normal result from the state.

For better understanding see code above.

First call

> const { body } = yield put.resolve(requestAsync({url: '/users'}));
console.log(body) // [{id: 1}, ...]

Second call
> const { body } = yield put.resolve(requestAsync({url: '/users'}));
console.log(body) // undefined

I think the problem in this condition https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L94

**Comment by ryanashcraft** [comment]
@vomchik I've explained this more in the 2.0 docs: https://github.com/amplitude/redux-query/tree/2.0#requestasync

Basically it won't return a promise if the middleware isn't going to make a network request. In this case it isn't making a network request because a previous request with the same query key succeeded. You can set `force: true` in the query config to override this behavior.

**Comment by vomchik** [comment]
hm, but why we can't return promise in all cases?

On May 12, 2017 18:27, "Ryan Ashcraft" <notifications@github.com> wrote:

Closed #77 <https://github.com/amplitude/redux-query/issues/77>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amplitude/redux-query/issues/77#event-1080179445>, or mute
the thread

**Comment by rogovdm** [comment]
> Basically it won't return a promise if the middleware isn't going to make a network request. 

@ryanashcraft can I ask, what is an intension for that behavior?

**Comment by ryanashcraft** [comment]
It's simply the API. You know if a promise is not returned that a network request will not be made, and you can handle this case appropriately if you'd like.

**Comment by rogovdm** [comment]
@ryanashcraft , got it. 

The other side is, that it `breaks` the workflow of nice-and-simple-chained-functions 😺 

What do you think about having an additional property that's saying, if the request actually happened?

**Comment by ryanashcraft** [comment]
@rogovdm It's a reasonable suggestion but for now I prefer the current API. 😊

**Comment by samuelcastro** [comment]
@ryanashcraft Even thought another request is not made on repeat requests, is there a way to just synchronously return the data rather than a Promise? Something like:

```
const data = dispatch(myQuery(...));
```
