### ISSUE TITLE
Throttling/query cancelation with redux-query

### ISSUE THREAD

**Issue by bstro** [amplitude/redux-query#80]
I'm currently dispatching queries on keyDown as the user types in a field. Obviously, this dispatches lots of requests. Sometimes these requests clobber the input as responses trickle back in, so the user's input characters are out of their intended order. I'm wondering about the best way to work with redux-query here. I am using `optimisticUpdate` to update the input field immediately. I see the following two options:

* Do some kind of throttling for such actions. This should mitigate most of the issue, but not all of it. We'll want to do this either way so our backend doesn't get hammered.
* Task cancelation (does redux-query already have this?). Is there a way to cancel inflight `mutateAsync` requests upon the dispatch of a new request of the same type?
* Perhaps related to task cancelation, maybe there's a way to only accept the most recent server response data into the store if there are multiple inflight `mutateAsync` requests.

Would love to hear your thoughts.

**Comment by ryanashcraft** [comment]
@bstro I don't think redux-query is optimized for this specific use case as you described. At Amplitude we'd usually store the input value in local React state or in a separate reducer. And then on some event (either triggered by redux-saga or some react event listener) we'd read from the state to dispatch a mutation. It'd just easier to do the "throttling" before redux-query comes into play. I would hazard against using entities for state that could be considered non-network state.

FYI You can cancel mutations with the `cancelQuery` action. We do that in the [redux-saga demo](https://amplitude.github.io/redux-query/#/redux-saga).
