### ISSUE TITLE
React as peer dependency

### ISSUE THREAD

**Issue by bstro** [amplitude/redux-query#86]
We use redux-query at my company as part of a large Ember application running Redux, and React as a peer dependency bloats our total javascript payload by a fair amount. Is there a way around this, or any possibility of separating redux-query's HOC to a different repo?

**Comment by ryanashcraft** [comment]
Yeah interesting. I've been thinking for a while splitting up the react component into a separate package (not a separate repo) for a while. The only downside is that it requires a little more overhead for the user when getting set up, but I think it's definitely the right thing to do long-term. This is also relevant as we've discussed internally open sourcing some additional redux-query utilities that really don't make sense in the main package.

Honestly no timeline for doing any of this, just writing down my thoughts. Off the top of my head here's what I'd like to see:

- Set up redux-query as a [Lerna](https://github.com/lerna/lerna) project.
- Decide if the superagent network interface belongs in the main project or not and how to handle the "advanced" entry point or ditch it. Does it make more sense to transition to a model where the superagent interface is in a separate package (i.e. `redux-query-superagent`)?
- Figure out a transition plan for existing users. The most painful thing will be importing `connectRequest`. Probably means at a minimum providing a codemod and doing a major bump.

**Comment by ryanashcraft** [comment]
redux-query-react is now published as a separate package so that apps that don't use React can use redux-query without having to worry about dealing with React as a peer dependency. Please see https://amplitude.github.io/redux-query/docs/upgrade-guides/v2-to-v3 for a guide on how to upgrade from v2 to 3.0.
