### ISSUE TITLE
Update field in action handler required but null check already in place

### ISSUE THREAD

**Issue by simenbrekken** [amplitude/redux-query#87]
Some of my mutations are simply request generators such as `sendEmail` where I'm really only interested in the result of the request itself.

In `query-advanced` [an invariant is thrown](https://github.com/amplitude/redux-query/blob/c2ec128721ca2647c57ada741db7250646fe1b19/src/middleware/query-advanced.js#L46) if `update` is missing from the request, but `updateEntities` [already handles update being null or undefined](https://github.com/amplitude/redux-query/blob/c2ec128721ca2647c57ada741db7250646fe1b19/src/lib/update.js#L2-L4)

I suggest either removing the invariant or replacing it `invariant(update === undefined)` so that it's possible to explicitly pass `update: null` if no updates are expected.

**Comment by simenbrekken** [comment]
@ryanashcraft It was late and I got it mixed up `mutate`. I ended up composing my own query function that included an `update: {}` in its default options. I still think it's worth removing the invariant though.

**Comment by ryanashcraft** [comment]
Having `update: {}` is no longer required with 3.0, which was just published. Please see https://amplitude.github.io/redux-query/docs/upgrade-guides/v2-to-v3 for a guide on how to upgrade from v2 to 3.0.
