### ISSUE TITLE
Move dependency on React to separate import

### ISSUE THREAD

**Issue by rplotkin** [amplitude/redux-query#93]
Currently writing an angular redux application, and I cannot use this library because it implodes without React. It's great to have React helper functions, but moving those to an import in redux-query/react, and keeping the redux-only code clean of non-redux things, would be solid.

**Comment by rplotkin** [comment]
I've created a PR that does what I suggest. It does work in my project. Possibly you'd want to only split it only in /advanced and /react?

**Comment by ryanashcraft** [comment]
Let's continue the conversation here: https://github.com/amplitude/redux-query/issues/86. I also replied to your PR.
