### ISSUE TITLE
Best way to log api response in redux-query

### ISSUE THREAD

**Issue by muscaiu** [amplitude/redux-query#95]
In this query example this would be the way to log the data received from the api?
Is there are other way then the `transform` object?

```
export function changeNameMutation(name, optimistic) {
        url: 'http://localhost:3333/api/change-name',
        options: { method: 'POST' },
        body: {
            name,
        },
        transform: (response) => {
            console.log('query ->', response)
        },
        update: {
            name: (prev, next) => {
                return next
            }
    }
}
```

**Comment by ryanashcraft** [comment]
@muscaiu From the query object itself? Yeah the best place is `transform`. If you want a more robust or general solution, I'd recommend logging with redux middleware (like redux-logger or something custom). Alternatively, you can always promise-chain on query/mutation actions to log the result.
