### ISSUE TITLE
Can "reject" be used to reject promises instead of resolve ? to catch promises errors  

### ISSUE THREAD

**Issue by tamerelsayed** [amplitude/redux-query#97]
In the source code, the promises are resolved in the resolve and the fail of the API calls [here](https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L141) and [here](https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L268) 

Is that intended for some reasons? 
In some cases, I want to catch the errors on the callback (for example in the submission of a form) and this "swallow" the errors.

```
 submitForm(values).catch(e => handleSubmissionError(e));
```

**Comment by ryanashcraft** [comment]
Hi @tamerelsayed. Yes, it was designed to not throw an Error when it receives a non-200 status code – just like `window.fetch`.

I'd recommend always checking `status` field in the `then` callback and conditionally throwing. You can make this a reusable function that does this for you (see the "handleErrors" function in https://www.tjvantoll.com/2015/09/13/fetch-and-errors/). Alternatively, you could compose the `mutateAsync` action and use that action whenever you'd normally use redux-query's `mutateAsync`.

**Comment by tamerelsayed** [comment]
Thanks, @ryanashcraft for the explanation. we follow something similar to "handleError" approach, the alternative approach seems interesting, will look into it.
