### ISSUE TITLE
difference between redux-query and redux-query-patch

### ISSUE THREAD

**Issue by Thebigbignooby** [amplitude/redux-query#98]
on npm, there are two different packages which point to this repo: 
https://www.npmjs.com/package/redux-query
https://www.npmjs.com/package/redux-query-patch

what are the differences ?
which one should we use - or why would we use one over the other ?

**Comment by ryanashcraft** [comment]
@Thebigbignooby I've never heard of redux-query-patch before. I'd use `redux-query` on npm/yarn.
